{
 "title": "JVM Monitoring",
 "description": "JVM monitoring by jmx_exporter host",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(jmx_exporter_build_info{job=\"jmx_exporter\"}, host)"
   },
   {
    "name": "jvm",
    "query": "label_values(jmx_exporter_build_info{job=\"jmx_exporter\", host=~\"$host\"}, jvm)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{host=~\"$host\", jvm=~\"$jvm\"}",
     "legendFormat": "{{area}} memory [{{jvm}}]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{host=~\"$host\", jvm=~\"$jvm\"}",
     "legendFormat": "current [{{jvm}}]"
    },
    {
     "expr": "jvm_threads_daemon{host=~\"$host\", jvm=~\"$jvm\"}",
     "legendFormat": "daemon [{{jvm}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{host=~\"$host\", jvm=~\"$jvm\"}",
     "legendFormat": "loaded [{{jvm}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{host=~\"$host\", jvm=~\"$jvm\"}[1m])",
     "legendFormat": "{{gc}} [{{jvm}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{host=~\"$host\", jvm=~\"$jvm\"}",
     "legendFormat": "{{gc}} [{{jvm}}]"
    }
   ]
  }
 ]
}